dist: xenial
language: minimal

git:
  quiet: true
  submodules: false

branches:
  only:
  - master
  - deploy

env:
# Carefull, also set it in the deploy section!
- NOTES_FILE=main

services:
- docker

script:
- docker run --rm -v $(pwd):/notes blang/latex /bin/bash -c "cd /notes; ./build.sh $NOTES_FILE"
- "./test.sh $NOTES_FILE"

deploy:
  provider: releases
  api_key:
    secure: eU27rvV7H/0vkMM61r7Q+ixBm1D/LxJvHKjcyeHTyklyGhx9g9kYm5ne2gnWKTYAAfykQbk1wl+IYaSSZ5+u1aVv2CRW1yoOiNVqpvSf3gfnjaSaRNRUvokO4rKU66eE5YeCM5+3p0VJqRgWVTWZJI99aTEXz39sjh3r2oVNXXyPtp5kBCr5iTre/LXWlC1g6YobOFhMmW7M28gOSX6uWKOvieFM+s7dJuROO726RjVCSrs7ZlVcD+MDpILNEkqFTtBnelcOEAZGoqf1L/VzhBOzesZlDULCKXiHoeoXgZTdsAkn/cODy7p9gCIWPTjYSRQj2NW5VY0hR5OLBWogO4gesxl+y2UM221r+Y9Ke3B6ZEy9KE3wi2lXY87pRw7mCrRRZHqYY+FI4ZADMZLqVFcsneqZ2uu++S3yA+/cKfyzHdqcjdvdFO9WhqODbV4crV4UxJ3q8+4ADWw18yC/AHry0AoebQsM7o/56h+y+F/lJhN++fHG7hmkOsZiYlhRneVcapvqRDMU3Kjju/AUJgKPr8FTzRvgOVa4sm2d+pxbk6sviaLb9iEjO7hZqwxQ2ewkMQAVUhBVw9MwIS1R6OOt2ATkntMN3H/qS0hbreGzM0Fq812yqWamxfWLRcJqpRUBfXQM0bKzkqJpHCmIzK8UXn0Sb7312f55UOqs1yY=
  file: main.pdf
  skip_cleanup: true
  on:
    repo: icl-notes/m3p65
